--!strict
local cardType = require(game.ReplicatedStorage.Types.Card)
return {
    {
        Id = "c387328f-0972-4ff9-8c81-f0c6d0e1zg04",
        Rarity = "Common",
        Probability = 1/2,

        DamageType = "c387328f-0972-4zz9-9881-f0c6d0e1zg04",
        DamageAmount = 1,

        ResistanceType = "c4182c2e-7101-42b2-b0db-98f961d4c0ed",
        ResistanceAmount = 1 / 2,

        WeaknessType = "z387528f-0972-4ff9-8s81-fgc6d0e1ff04",
        WeaknessAmount = 1 / 4,

        MaxHeath = 25,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD",
        DisplayName = "Example Card",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description",
    },
    {
        Id = "a9d0b6c1-3b68-45e4-a902-9c7292a1c6b2",
        Rarity = "Common",
        Probability = 1/4,

        DamageType = "f7b39490-27c7-4e3b-88f4-72253f42f1ee",
        DamageAmount = 2,

        ResistanceType = "ba5b5925-1cb2-49a5-99a2-f06e7b7e6501",
        ResistanceAmount = 1 / 2,

        WeaknessType = "cd5c6ecb-d536-4eb0-9d3e-518b9a8e1d3f",
        WeaknessAmount = 1 / 4,

        MaxHeath = 30,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_2",
        DisplayName = "Example Card 2",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 2",
    },
    -- Add 23 more entries
    {
        Id = "b3a98c18-47c1-491e-baeb-5d87c7cbab0f",
        Rarity = "Common",
        Probability = 1/6,

        DamageType = "e5d67b33-00d9-4b91-81e0-670aadcc8b84",
        DamageAmount = 3,

        ResistanceType = "f8a1de54-3d38-4485-a732-1a3c93ae764b",
        ResistanceAmount = 1 / 2,

        WeaknessType = "d9b8e766-ee3d-4a0b-a063-df2a4db8ed8f",
        WeaknessAmount = 1 / 4,

        MaxHeath = 35,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_3",
        DisplayName = "Example Card 3",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 3",
    },
    {
        Id = "7db4912d-dcb1-4bc9-86a5-6e049d3ed5d1",
        Rarity = "Common",
        Probability = 1/10,

        DamageType = "c2c3df94-0f88-48b4-81a0-4ae3b3dcba5c",
        DamageAmount = 4,

        ResistanceType = "e3f261cd-9599-4a69-898f-b2b35d5e0918",
        ResistanceAmount = 1 / 2,

        WeaknessType = "f27a6bbf-39c6-43d2-aae3-2626ad4d99f3",
        WeaknessAmount = 1 / 4,

        MaxHeath = 40,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_4",
        DisplayName = "Example Card 4",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 4",
    },
    {
        Id = "0a5d860b-3936-422b-b39e-2c122fb76d6a",
        Rarity = "Common",
        Probability = 1/20,

        DamageType = "b1c6a0fe-4f14-4b4e-ba3e-4e68a0515054",
        DamageAmount = 5,

        ResistanceType = "bd7db0a1-3c69-4e9e-bb7c-df0f1a5c4f87",
        ResistanceAmount = 1 / 2,

        WeaknessType = "f674e1e5-9495-4395-948a-6ed7f3099f7d",
        WeaknessAmount = 1 / 4,

        MaxHeath = 45,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_5",
        DisplayName = "Example Card 5",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 5",
    },
    {
        Id = "c50b5c38-6db7-4d53-91b4-26e01d9b34f9",
        Rarity = "Common",
        Probability = 1/50,

        DamageType = "fa8c1b3a-2588-4cbb-8271-ef89d7fde16c",
        DamageAmount = 6,

        ResistanceType = "d3202355-9186-4d46-bc09-45c589cf62bf",
        ResistanceAmount = 1 / 2,

        WeaknessType = "fbc4d5b9-8f38-4b22-bba6-ead406139ca9",
        WeaknessAmount = 1 / 4,

        MaxHeath = 50,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_6",
        DisplayName = "Example Card 6",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 6",
    },
    {
        Id = "81c0b7b4-4082-431d-8d87-150b09f5c4f6",
        Rarity = "Common",
        Probability = 1/60,

        DamageType = "a57e05c3-038f-4204-bd1a-f68cb6297b9a",
        DamageAmount = 7,

        ResistanceType = "c20cf2ff-f0f2-464b-b291-f6095a21843d",
        ResistanceAmount = 1 / 2,

        WeaknessType = "d520f5ed-8317-4041-b62e-2dcb2b50ff79",
        WeaknessAmount = 1 / 4,

        MaxHeath = 55,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_7",
        DisplayName = "Example Card 7",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 7",
    },
    {
        Id = "a0d5b7c1-495d-4c50-80f1-8586d4c5e63e",
        Rarity = "Common",
        Probability = 1/70,

        DamageType = "b301bc86-9b3f-4891-b3f0-834081f3ed36",
        DamageAmount = 8,

        ResistanceType = "cf240978-1333-4f51-8142-f885fc4fd964",
        ResistanceAmount = 1 / 2,

        WeaknessType = "b1076ff2-9b49-4946-a6b5-5792fb6e3d70",
        WeaknessAmount = 1 / 4,

        MaxHeath = 60,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_8",
        DisplayName = "Example Card 8",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 8",
    },
    {
        Id = "28fd8e0b-13e4-41df-9d02-175ecdd47210",
        Rarity = "Common",
        Probability = 1/85,

        DamageType = "ffac4d98-1058-4821-a7fd-30558e697dcd",
        DamageAmount = 9,

        ResistanceType = "ae7346ff-14c3-4dd1-90c2-14c482a824f7",
        ResistanceAmount = 1 / 2,

        WeaknessType = "a257acfc-1958-4d9b-84c7-2bb30b607e14",
        WeaknessAmount = 1 / 4,

        MaxHeath = 65,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_9",
        DisplayName = "Example Card 9",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 9",
    },
    {
        Id = "6c9f88de-7322-4a8e-8d4e-1c68cb80ed91",
        Rarity = "Common",
        Probability = 1/95,

        DamageType = "e8efb6e9-d21d-4690-bb82-9e90de79a8c2",
        DamageAmount = 10,

        ResistanceType = "c3a48088-c86d-4621-9857-38bfb326161d",
        ResistanceAmount = 1 / 2,

        WeaknessType = "dd46d165-76a1-4bb5-9968-5e568e8c4bf2",
        WeaknessAmount = 1 / 4,

        MaxHeath = 70,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_10",
        DisplayName = "Example Card 10",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 10",
    },
    {
        Id = "e408b379-f405-437f-8e12-f31c5a7af68d",
        Rarity = "Common",
        Probability = 1/105,

        DamageType = "d52b3030-0d9c-4033-95e8-1a187d98d8d2",
        DamageAmount = 11,

        ResistanceType = "a19399f3-170d-46de-8a33-187d8b68df1d",
        ResistanceAmount = 1 / 2,

        WeaknessType = "e349044c-79a3-41fc-b628-057e0f3e9355",
        WeaknessAmount = 1 / 4,

        MaxHeath = 75,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_11",
        DisplayName = "Example Card 11",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 11",
    },
    {
        Id = "b2145c94-3ed2-467d-9d54-393cb578ba74",
        Rarity = "Common",
        Probability = 1/110,

        DamageType = "d0a986d3-1bf5-4f44-b55c-d1a23214e47c",
        DamageAmount = 12,

        ResistanceType = "f2b85c06-7fe3-4592-9d3d-9b413b8cc07e",
        ResistanceAmount = 1 / 2,

        WeaknessType = "b0e5f5fc-d9d5-4d13-8329-49aa1a9c6058",
        WeaknessAmount = 1 / 4,

        MaxHeath = 80,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_12",
        DisplayName = "Example Card 12",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 12",
    },
    {
        Id = "d22d8b09-bb36-4f4c-b5d9-6cde9ae36a8a",
        Rarity = "Common",
        Probability = 1/120,

        DamageType = "dc538aaf-5c7b-493d-856b-eb202a05b663",
        DamageAmount = 13,

        ResistanceType = "be07ee11-7b3c-49d0-bb9a-8f0b43d746df",
        ResistanceAmount = 1 / 2,

        WeaknessType = "f7b6bcf0-84b0-4548-b59a-95c0e2b7bb18",
        WeaknessAmount = 1 / 4,

        MaxHeath = 85,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_13",
        DisplayName = "Example Card 13",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 13",
    },
    {
        Id = "12eb33f2-c3eb-446e-b71a-2d24d7c446b1",
        Rarity = "Common",
        Probability = 1/130,

        DamageType = "ec00a6d4-65d7-4987-9126-f87882604605",
        DamageAmount = 14,

        ResistanceType = "e4826579-fb25-4705-8e26-69a1e07a77ec",
        ResistanceAmount = 1 / 2,

        WeaknessType = "d667d98e-c60a-4c0c-b11d-f51c7f8c3ad3",
        WeaknessAmount = 1 / 4,

        MaxHeath = 90,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_14",
        DisplayName = "Example Card 14",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 14",
    },
    {
        Id = "19057f37-b055-4f15-b90d-f7bca8de2e2c",
        Rarity = "Common",
        Probability = 1/250,

        DamageType = "b99c3f5b-7a7c-4d07-87b9-b5ac4b0e57f8",
        DamageAmount = 15,

        ResistanceType = "ef1d0125-28f1-4ddc-b742-ae354f057f3e",
        ResistanceAmount = 1 / 2,

        WeaknessType = "c050a6b3-085f-4b6b-8a7f-0be5c32a67b8",
        WeaknessAmount = 1 / 4,

        MaxHeath = 95,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_15",
        DisplayName = "Example Card 15",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 15",
    },
    {
        Id = "d0e8d71a-7b6a-491b-a258-4dd55c52f684",
        Rarity = "Common",
        Probability = 1/300,

        DamageType = "d343f8d8-96a5-4d24-86e9-c2b250af3a7c",
        DamageAmount = 16,

        ResistanceType = "b52554e3-520d-4850-88f0-6c96d8cdcc2f",
        ResistanceAmount = 1 / 2,

        WeaknessType = "d9da2b1a-af08-4d9c-b81c-b2c12e3a1bb5",
        WeaknessAmount = 1 / 4,

        MaxHeath = 100,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_16",
        DisplayName = "Example Card 16",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 16",
    },
    {
        Id = "0bf9d299-7dab-49af-9e7b-2c92d99c25a0",
        Rarity = "Common",
        Probability = 1/400,

        DamageType = "b45fe9a9-3122-4682-b4c4-0285f2f755f1",
        DamageAmount = 17,

        ResistanceType = "f29a899d-036f-469b-ae05-46ff6eb264f7",
        ResistanceAmount = 1 / 2,

        WeaknessType = "a80ee1af-4082-4bfa-9d2f-f3c0e5d19f85",
        WeaknessAmount = 1 / 4,

        MaxHeath = 105,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_17",
        DisplayName = "Example Card 17",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 17",
    },
    {
        Id = "c163e3d9-45cd-40f5-8411-0e26a3b50e12",
        Rarity = "Common",
        Probability = 1/450,

        DamageType = "f2b3b09d-9c3c-4b7b-8b2d-3e9865a22c30",
        DamageAmount = 18,

        ResistanceType = "d5b2cfea-5202-4318-ba32-73fe9eab48a2",
        ResistanceAmount = 1 / 2,

        WeaknessType = "a80ee1af-4082-4bfa-9d2f-f3c0e5d19f85",
        WeaknessAmount = 1 / 4,

        MaxHeath = 110,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_18",
        DisplayName = "Example Card 18",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 18",
    },
    {
        Id = "5ad3d03d-fd2f-4e5c-b8a4-670c239c8f07",
        Rarity = "Common",
        Probability = 1/500,

        DamageType = "d2d4c5ff-9a8f-4e54-b041-d1d63aa7c36d",
        DamageAmount = 19,

        ResistanceType = "a91b9a91-8a71-41f0-bdf1-9e8de1b1ab37",
        ResistanceAmount = 1 / 2,

        WeaknessType = "f1f59b7e-d300-4c91-a42d-0343ec55aa27",
        WeaknessAmount = 1 / 4,

        MaxHeath = 115,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_19",
        DisplayName = "Example Card 19",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 19",
    },
    {
        Id = "a003ce74-af10-4e51-b0bb-57d615f3a367",
        Rarity = "Common",
        Probability = 1/600,

        DamageType = "f1f59b7e-d300-4c91-a42d-0343ec55aa27",
        DamageAmount = 20,

        ResistanceType = "d2d4c5ff-9a8f-4e54-b041-d1d63aa7c36d",
        ResistanceAmount = 1 / 2,

        WeaknessType = "a91b9a91-8a71-41f0-bdf1-9e8de1b1ab37",
        WeaknessAmount = 1 / 4,

        MaxHeath = 120,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_20",
        DisplayName = "Example Card 20",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 20",
    },
    {
        Id = "7a6c5fa4-734d-4e7b-8d6c-0163c586d394",
        Rarity = "Common",
        Probability = 1/700,

        DamageType = "f2b3b09d-9c3c-4b7b-8b2d-3e9865a22c30",
        DamageAmount = 21,

        ResistanceType = "d5b2cfea-5202-4318-ba32-73fe9eab48a2",
        ResistanceAmount = 1 / 2,

        WeaknessType = "a80ee1af-4082-4bfa-9d2f-f3c0e5d19f85",
        WeaknessAmount = 1 / 4,

        MaxHeath = 125,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_21",
        DisplayName = "Example Card 21",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 21",
    },
    {
        Id = "c6899bb5-5de8-4ae4-a6e2-492622d43a12",
        Rarity = "Common",
        Probability = 1/800,

        DamageType = "d2d4c5ff-9a8f-4e54-b041-d1d63aa7c36d",
        DamageAmount = 22,

        ResistanceType = "a91b9a91-8a71-41f0-bdf1-9e8de1b1ab37",
        ResistanceAmount = 1 / 2,

        WeaknessType = "f1f59b7e-d300-4c91-a42d-0343ec55aa27",
        WeaknessAmount = 1 / 4,

        MaxHeath = 130,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_22",
        DisplayName = "Example Card 22",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 22",
    },
    {
        Id = "a1f5e8de-1b30-4a8f-8b0f-ded026ed8cf2",
        Rarity = "Common",
        Probability = 1/900,

        DamageType = "a91b9a91-8a71-41f0-bdf1-9e8de1b1ab37",
        DamageAmount = 23,

        ResistanceType = "f1f59b7e-d300-4c91-a42d-0343ec55aa27",
        ResistanceAmount = 1 / 2,

        WeaknessType = "d2d4c5ff-9a8f-4e54-b041-d1d63aa7c36d",
        WeaknessAmount = 1 / 4,

        MaxHeath = 135,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_23",
        DisplayName = "Example Card 23",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 23",
    },
    {
        Id = "fb94da22-b8e4-4680-bf53-29cd9f1fa635",
        Rarity = "Common",
        Probability = 1/1000,

        DamageType = "f2b3b09d-9c3c-4b7b-8b2d-3e9865a22c30",
        DamageAmount = 24,

        ResistanceType = "d5b2cfea-5202-4318-ba32-73fe9eab48a2",
        ResistanceAmount = 1 / 2,

        WeaknessType = "a80ee1af-4082-4bfa-9d2f-f3c0e5d19f85",
        WeaknessAmount = 1 / 4,

        MaxHeath = 140,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_24",
        DisplayName = "Example Card 24",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 24",
    },
    {
        Id = "63ff8b07-0755-42de-a103-7e7a8c3cb3a7",
        Rarity = "Common",
        Probability = 1/1500,

        DamageType = "d2d4c5ff-9a8f-4e54-b041-d1d63aa7c36d",
        DamageAmount = 25,

        ResistanceType = "a91b9a91-8a71-41f0-bdf1-9e8de1b1ab37",
        ResistanceAmount = 1 / 2,

        WeaknessType = "f1f59b7e-d300-4c91-a42d-0343ec55aa27",
        WeaknessAmount = 1 / 4,

        MaxHeath = 145,

        --Display Info
        Type = "Card",
        ImageUrl = "",
        SystemName = "EXAMPLE_CARD_25",
        DisplayName = "Example Card 25",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Description = "Example Description 25",
    },
} :: {cardType.Card}
