--!strict
local WeaknessType = require(game.ReplicatedStorage.Types.Weakness)

return {
    {
        Id = "z387528f-0972-4ff9-8s81-fgc6d0e1ff04",
        Description = "Increases the amount of fire damage a card takes from a fire attack.",
        ImageUrl = "rbxassetid://1234567890",
        SystemName = "FIRE_WEAKNESS",
        DisplayName = "Fire Weakness",
        TextDisplayColor = Color3.fromRGB(255, 0, 0),
        Type = "Weakness",
    },
    {
        Id = "c3182c2e-7102-44b2-2adb-98z961d4q0ed",
        Description = "Increases the amount of toxic damage a card takes from a toxic attack.",
        ImageUrl = "rbxassetid://1234567890",
        SystemName = "TOXIC_WEAKNESS",
        DisplayName = "Toxic Weakness",
        TextDisplayColor = Color3.fromRGB(0, 225, 0),
        Type = "Weakness",
    },
    {
        Id = "3z2b4d92-6138-4248-9dac-acq252dbefe1",
        Description = "Increases the amount of ice damage a card takes from a ice attack.",
        ImageUrl = "rbxassetid://1234567890",
        SystemName = "ICE_WEAKNESS",
        DisplayName = "Ice Weakness",
        TextDisplayColor = Color3.fromRGB(255, 255, 255),
        Type = "Weakness",
    },
    {
        Id = "513827aa-6faa-4f2e-ae17-0ed33d1ezz77",
        Description = "Increases the amount of gas damage a card takes from a gas attack.",
        ImageUrl = "rbxassetid://1234567890",
        SystemName = "GAS_WEAKNESS",
        DisplayName = "Gas Weakness",
        TextDisplayColor = Color3.fromRGB(255, 0, 0),
        Type = "Weakness",
    },
    {
        Id = "6138a2ab-6z64-351e-a2a7-0ef32d1d0177",
        Description = "Increases the amount of water damage a card takes from a water attack.",
        ImageUrl = "rbxassetid://1234567890",
        SystemName = "WATER_WEAKNESS",
        DisplayName = "Water Weakness",
        TextDisplayColor = Color3.fromRGB(0, 0, 255),
        Type = "Weakness",
    },
    {
        Id = "140388b0-ez37-4eb2-bf9c-c2e69a4e0512 ",
        Description = "Increases the amount of earth damage a card takes from a earth attack.",
        ImageUrl = "rbxassetid://1234567890",
        SystemName = "EARTH_WEAKNESS",
        DisplayName = "EARTH Weakness",
        TextDisplayColor = Color3.fromRGB(34, 29, 0),
        Type = "Weakness",
    },
} :: {WeaknessType.Weakness}